var res = {
    helloBG_png  : "res/helloBG.png",
    start_n_png  : "res/start_n.png",
    start_s_png  : "res/start_s.png",
    PlayBG_png   : "res/PlayBG.png",
    runner_png   : "res/running.png",
    runner_plist  : "res/running.plist",
    akuma_png    : "res/akuma-running.png",
    akuma_plist   : "res/akuma-running.plist",
    leftbutton_png: "res/leftbutton.png",
    rightbutton_png: "res/rightbutton.png",

    sfx_punch    : "res/sfx/punch.wav",
    sfx_hadoken  : "res/sfx/hadoken.wav",
    sfx_hit      : "res/sfx/hit.wav",
    sfx_jump     : "res/sfx/jump.wav",
    sfx_ko       : "res/sfx/ko.wav",
    sfx_clash    : "res/sfx/clash.wav",
    sfx_round    : "res/sfx/round.wav",
    sfx_music    : "res/sfx/music.wav",
    sfx_fight    : "res/sfx/fight.wav",
    sfx_one      : "res/sfx/one.wav",
    sfx_youwin   : "res/sfx/youwin.wav",
    sfx_youlose  : "res/sfx/youlose.wav",
    sfx_perfect  : "res/sfx/perfect.wav",
    sfx_shoryuken: "res/sfx/shoryuken.wav",
    sfx_fierce   : "res/sfx/fierce_hit.wav",
    sfx_hard     : "res/sfx/hard_attack.wav",
    sfx_hitground: "res/sfx/hitground.wav",
    sfx_crowd    : "res/sfx/crowd.wav",
    sfx_select   : "res/sfx/select.wav",
    sfx_cursor   : "res/sfx/cursor.wav",
    sfx_countdown: "res/sfx/countdown_tick.wav",
    sfx_count3   : "res/sfx/count3.wav",
    sfx_count2   : "res/sfx/count2.wav",
    sfx_count1   : "res/sfx/count1.wav"
};

var g_resources = [
    res.helloBG_png,
    res.start_n_png,
    res.start_s_png,
    res.PlayBG_png,
    res.runner_png,
    res.runner_plist,
    res.akuma_png,
    res.akuma_plist,
    res.leftbutton_png,
    res.rightbutton_png,
    res.sfx_punch, res.sfx_hadoken, res.sfx_hit, res.sfx_jump,
    res.sfx_ko, res.sfx_clash, res.sfx_round, res.sfx_music,
    res.sfx_fight, res.sfx_one, res.sfx_youwin, res.sfx_youlose,
    res.sfx_perfect, res.sfx_shoryuken, res.sfx_fierce, res.sfx_hard,
    res.sfx_hitground, res.sfx_crowd, res.sfx_select, res.sfx_cursor,
    res.sfx_countdown, res.sfx_count3, res.sfx_count2, res.sfx_count1
];
